---
fail_fast: false
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-yaml
      - id: check-builtin-literals
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  # until ruff can detect dead code, use this:
  - repo: https://github.com/asottile/dead
    rev: v2.1.0
    hooks:
      - id: dead
        args:
          - --tests
          - test_.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # Run the linter
      - id: ruff
        args:
          - --fix
          - --show-fixes
      # Run the formatter
      - id: ruff-format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args: []
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args:
          - -x
          - tests
        stages:
          - pre-push
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args:
          - --fix
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.17.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
      - id: poetry-check
