FROM python:3.12-slim-bookworm

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root --no-interaction --no-ansi --without dev

COPY monitor monitor/

ENTRYPOINT ["poetry", "run", "python3", "-m", "monitor.collector"]
