---
check_interval: 60
kafka:
  host: 'kafka-abc.kafkacloud.com:27436'
  certfile: 'certs/service.cert'
  keyfile: 'certs/service.key'
  cafile: 'certs/ca.pem'
postgres:
  uri: 'postgres://metrics-writer:1234567890@pg-xyz.postgrescloud.io:27434/metrics?sslmode=require'
websites:
  - url: 'https://github.com'
    regex: 'Pull requests'
  - url: 'https://www.postgresql.org/'
    regex: 'MySQL'
  - url: 'https://google.com'
