---
check_interval: 60
kafka:
  host: localhost:9092
postgres:
  uri: postgres://postgres:1234567890@localhost:5432/?sslmode=prefer
websites:
  - url: https://github.com
    regex: Pull requests
  - url: https://www.postgresql.org/
    regex: MySQL
  - url: https://google.com
