[tool.poetry]
name = "monitor"
version = "0.1.1"
description = "Small conceptual website monitor using Kafka and PostgreSQL."
authors = ["Sören König <soeren.koenig@mailbox.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/skoenig/website-monitor"

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "6.0.2"
apscheduler = "^3.6.3"
requests = "^2.32"
kafka-python = "2.0.6"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
pytest = ">=7.2.0"
pylint = "^2.5.3"
coverage = "^5.1"
pre-commit = "*"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
