[tool.poetry]
name = "monitor"
version = "0.1.0"
description = "Small conceptual website monitor using Kafka and PostgreSQL."
authors = ["Sören König <soeren.koenig@mailbox.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/skoenig/website-monitor"

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.4"
apscheduler = "^3.6.3"
requests = "^2.23.0"
kafka-python = ">=1.4.7"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"
coverage = "^5.1"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
